### ISSUE TITLE
Add README.md for each application

### ISSUE THREAD

**Issue by tracker1** [jfrazelle/dockerfiles#10]
It would be nice to have a README.md for each application that included a command-line to run the application in a container (esp. the gui apps).

Another suggestion, would be to have an `app-name.sh` shell script that ran said command.

**Comment by Juev** [comment]
+1

**Comment by willis7** [comment]
There's some good commentary in the Dockerfile itself. Here's one example:

```
# VERSION:        0.1
# DESCRIPTION:    Create the atom editor in a container 
# AUTHOR:         Jessica Frazelle <jess@docker.com>
# COMMENTS:
#   This file describes how to build the atom editor 
#   in a container with all dependencies installed.
#   Note: atom is not a node-webkit app,
#   found this out a little too late into this example
#   it uses atom-shell(https://github.com/atom/atom-shell)
#   Tested on Debian Jessie.
# USAGE:
#   # Download atom Dockerfile
#   wget http://raw.githubusercontent.com/jfrazelle/dockerfiles/master/atom/Dockerfile
#
#   # Build atom image
#   docker build -t atom .
#
#   docker run -v /tmp/.X11-unix:/tmp/.X11-unix \
#     -e DISPLAY=unix$DISPLAY atom
#
```

**Comment by jfrazelle** [comment]
ok i think almost all have instructions at the top now

**Comment by veerendra2** [comment]
Not sure, how to start firefox container. 

https://github.com/jessfraz/dockerfiles/blob/master/firefox/Dockerfile

```
veeru@ghost:~$ sudo docker run --rm r.j3ss.co/firefox:latest

(firefox:1): Gtk-WARNING **: 17:52:50.701: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: no DISPLAY environment variable specified

```

Any help?

**Comment by jelinekb** [comment]
This worked for me (see [https://github.com/jessfraz/dotfiles/blob/master/.dockerfunc](url))

xhost + # caution: may not be secure

docker run -d \
	--tmpfs /dev/shm \
	--net host \
	--cpuset-cpus 0 \
	-v /etc/localtime:/etc/localtime:ro \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v "${HOME}/.firefox/cache:/root/.cache/mozilla" \
	-v "${HOME}/.firefox/mozilla:/root/.mozilla" \
	-v "${HOME}/Downloads:/root/Downloads" \
	-v "${HOME}/Pictures:/root/Pictures" \
	-v "${HOME}/Torrents:/root/Torrents" \
	-e "DISPLAY=${DISPLAY}" \
	-e GDK_SCALE \
	-e GDK_DPI_SCALE \
	--device /dev/snd \
	--device /dev/dri \
	--name firefox \
	jess/firefox "$@"

NOTES:
Replaced "--memory 2gb" with "--tmpfs /dev/shm" to address tab crashes (see [)](https://github.com/jessfraz/dockerfiles/issues/490)

Replaced -e "DISPLAY=unix${DISPLAY}" \ with 	-e "DISPLAY=${DISPLAY}" \ to connect to local host on Ubuntu

Replaced ${DOCKER_REPO_PREFIX}/firefox "$@" with hardcoded jess/firefox "$@"
