### ISSUE TITLE
Unable to start jess/gparted on OS X El Capitan

### ISSUE THREAD

**Issue by pericazivkovic** [jfrazelle/dockerfiles#101]
Hi there,

was excited to read on your blog about how to run desktop apps in docker on OSX, however I have some issues to get it working:

```
docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/sda:/dev/sda --name gparted jess/gparted
Unable to find image 'jess/gparted:latest' locally
latest: Pulling from jess/gparted
523ef1d23f22: Pull complete 
140f9bdfeb97: Pull complete 
fc56060664de: Pull complete 
ddb241964ad8: Pull complete 
a003b543bde0: Pull complete 
Digest: sha256:cca27f1701433c5e4a343907b92f8649bdc4818acea5e76cb27fd7c61e6d98af
Status: Downloaded newer image for jess/gparted:latest

(gpartedbin:25): Gtk-WARNING **: cannot open display: unix
```

Other examples, like jess/htop that don't need display do work.

any comments/help will be very appreciated.

Thank you for this repository, it is very useful!

**Comment by jfrazelle** [comment]
You didn't read the blog if you running this on OS X;) I clearly say it
won't work and link to a workaround

On Saturday, January 16, 2016, Perica Zivkovic <notifications@github.com>
wrote:

> Hi there,
>
> was excited to read on your blog about how to run desktop apps in docker
> on OSX, however I have some issues to get it working:
>
> docker run -it -v /tmp/X11-unix:/tmp/X11-unix -e DISPLAY=unix$DISPLAY --device /dev/sda:/dev/sda --name gparted jess/gparted
> Unable to find image 'jess/gparted:latest' locally
> latest: Pulling from jess/gparted
> 523ef1d23f22: Pull complete
> 140f9bdfeb97: Pull complete
> fc56060664de: Pull complete
> ddb241964ad8: Pull complete
> a003b543bde0: Pull complete
> Digest: sha256:cca27f1701433c5e4a343907b92f8649bdc4818acea5e76cb27fd7c61e6d98af
> Status: Downloaded newer image for jess/gparted:latest
>
> (gpartedbin:25): Gtk-WARNING **: cannot open display: unix
>
> Other examples, like jess/htop that don't need display do work
>
> any comments/help will be very appreciated
>
> Thank you for this repository, it is very useful!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/101>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by pericazivkovic** [comment]
Oh! Thanks a lot for clarifying!
