### ISSUE TITLE
jfrazelle/dockerfiles/openvpn/ small difficulty certs

### ISSUE THREAD

**Issue by jonathanstiansen** [jfrazelle/dockerfiles#104]
So this is totally my stupidity, and likely just a lack of understanding of OpenVPN - but I'm attempting to use certificates and keys with this, and I'm getting this issue:
```
jono@macbook:~/projects/vpn-client% docker-compose run vpn myConfig.opvn 
Options error: --ca fails with '/etc/openvpn/ca.crt': No such file or directory
Options error: --cert fails with 'local.crt': No such file or directory
Options error: --key fails with 'local.key': No such file or directory
```
I've added this line to the docker file to put the certs and  key into the `etc/openvpn/` folder:
```
WORKDIR /etc/openvpn

COPY additional_files/* $WORKDIR/

ENTRYPOINT ["openvpn"]
```
If you notice in the error, I was attempting to test my understanding with the `/etc/openvpn/ca.crt` to see if hardcoding the path it would find that correctly, but no such luck.

Any advice?

**Comment by jfrazelle** [comment]
You can run with -v and mount the files into the container
