### ISSUE TITLE
chromium libpng12-0 error

### ISSUE THREAD

**Issue by brad-alexander** [jfrazelle/dockerfiles#108]
Getting 

`E: The package index files are corrupted. No Filename: field for package libpng12-0.`

when trying to build chromium.

**Comment by jfrazelle** [comment]
yeah its an apt thing

On Wed, Feb 3, 2016 at 4:06 PM, brad-alexander <notifications@github.com>
wrote:

> Getting
>
> E: The package index files are corrupted. No Filename: field for package
> libpng12-0.
>
> when trying to build chromium.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/108>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
not a docker problem so closing

On Wed, Feb 3, 2016 at 4:13 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> yeah its an apt thing
>
> On Wed, Feb 3, 2016 at 4:06 PM, brad-alexander <notifications@github.com>
> wrote:
>
>> Getting
>>
>> E: The package index files are corrupted. No Filename: field for package
>> libpng12-0.
>>
>> when trying to build chromium.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/108>.
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by brad-alexander** [comment]
so expected until apt fixes?

**Comment by jfrazelle** [comment]
ya i mean i bet they just uploaded a bad package and you happened to catch
it then i would just wait

On Wed, Feb 3, 2016 at 4:15 PM, brad-alexander <notifications@github.com>
wrote:

> so expected until apt fixes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/108#issuecomment-179545731>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
you can pull mine

On Wed, Feb 3, 2016 at 4:15 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> ya i mean i bet they just uploaded a bad package and you happened to catch
> it then i would just wait
>
> On Wed, Feb 3, 2016 at 4:15 PM, brad-alexander <notifications@github.com>
> wrote:
>
>> so expected until apt fixes?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/108#issuecomment-179545731>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
