### ISSUE TITLE
ykpersonalize: "ps: command not found"

### ISSUE THREAD

**Issue by pwFoo** [jfrazelle/dockerfiles#109]
I get the following error message:
`/usr/local/bin/entrypoint.sh: line 4: ps: command not found`

Solution:
`apt-get update && apt-get install procps`

**Comment by jfrazelle** [comment]
Why do you need ps

On Saturday, February 6, 2016, pwFoo <notifications@github.com> wrote:

> I get the following error message:
> /usr/local/bin/entrypointsh: line 4: ps: command not found
>
> Solution:
> apt-get update && apt-get install procps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/109>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by pwFoo** [comment]
It's used in your entrypoint.sh. 
`local pcscd_running=$(ps -aux | grep [p]cscd)`

During container start I get the following error message:
`/usr/local/bin/entrypoint.sh: line 4: ps: command not found`

**Comment by jfrazelle** [comment]
Oh lol I'll update the entry point

On Saturday, February 6, 2016, pwFoo <notifications@github.com> wrote:

> It's used in your entrypoint.sh.
> local pcscd_running=$(ps -aux | grep [p]cscd)
>
> During container start I get the following error message:
> /usr/local/bin/entrypoint.sh: line 4: ps: command not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/109#issuecomment-180777302>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
