### ISSUE TITLE
pkiclient / Safenet Authentication client as container?

### ISSUE THREAD

**Issue by pwFoo** [jfrazelle/dockerfiles#110]
I use a Aladdin eToken with Windows and would also use it with my Linux PC for pubkey ssh auth. Is it possible to create a docker container with Safenet Authentication client / pkiclient for eToken support?

**Comment by jfrazelle** [comment]
You can put anything in a container you just install it as you would on
Linux ;) but honestly for docker questions you might wanna try #docker-dev
irc instead

On Saturday, February 6, 2016, pwFoo <notifications@github.com> wrote:

> I use a Aladdin eToken with Windows and would also use it with my Linux PC
> for pubkey ssh auth Is it possible to create a docker container with
> Safenet Authentication client / pkiclient for eToken support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/110>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Meant #docker on irc

On Saturday, February 6, 2016, Jessica Frazelle <me@jessfraz.com> wrote:

> You can put anything in a container you just install it as you would on
> Linux ;) but honestly for docker questions you might wanna try #docker-dev
> irc instead
>
> On Saturday, February 6, 2016, pwFoo <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I use a Aladdin eToken with Windows and would also use it with my Linux
>> PC for pubkey ssh auth Is it possible to create a docker container with
>> Safenet Authentication client / pkiclient for eToken support?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/110>.
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
The point of this repo is for my personal needs not an image library for
everyone's ;)

On Saturday, February 6, 2016, Jessica Frazelle <me@jessfraz.com> wrote:

> Meant #docker on irc
>
> On Saturday, February 6, 2016, Jessica Frazelle <me@jessfraz.com
> <javascript:_e(%7B%7D,'cvml','me@jessfraz.com');>> wrote:
>
>> You can put anything in a container you just install it as you would on
>> Linux ;) but honestly for docker questions you might wanna try #docker-dev
>> irc instead
>>
>> On Saturday, February 6, 2016, pwFoo <notifications@github.com> wrote:
>>
>>> I use a Aladdin eToken with Windows and would also use it with my Linux
>>> PC for pubkey ssh auth Is it possible to create a docker container with
>>> Safenet Authentication client / pkiclient for eToken support?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/jfrazelle/dockerfiles/issues/110>.
>>>
>>
>>
>> --
>>
>>
>> Jessie Frazelle
>> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
>> pgp.mit.edu
>> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>>
>>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by pwFoo** [comment]
Thanks for your answer!

I tried to install pkiclient to a centos6 container, but start of my test build failed with a segfault. I think because of missing dependencies / needed running processes. No experience with pkiclient / safenet client and linux yet and won't move to a centos 6 desktop install (to be compatible to the pkiclient). 

I'll do some more tests and maybe follow your hint and try #docker on irc. Thanks.
