### ISSUE TITLE
Use of USER

### ISSUE THREAD

**Issue by EtienneBruines** [jfrazelle/dockerfiles#114]
I'm following the nice blog post [here](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/), about Chrome inside Docker. 

I've noticed the runtime binding `-v $HOME/Downloads:/root/Downloads \ # optional, but nice`. 

Why does it run as root? Instead of as some user / nobody? Can it run without root?

**Comment by jfrazelle** [comment]
with Docker 1.10 you can run it with userns

On Wed, Feb 17, 2016 at 7:46 AM, Etienne Bruines <notifications@github.com>
wrote:

> I'm following the nice blog post here
> <https://blog.jessfraz.com/post/docker-containers-on-the-desktop/>, about
> Chrome inside Docker.
>
> I've noticed the runtime binding -v $HOME/Downloads:/root/Downloads \ #
> optional, but nice.
>
> Why does it run as root? Instead of as some user / nobody? Can it run
> without root?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/114>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by EtienneBruines** [comment]
That just blew my mind away. (Thank you for the reference!) According to the [release blog](https://blog.docker.com/2016/02/docker-engine-1-10-security/), all I have to do is run docker with the `--userns-remap`, without changes to the container / run command. 

Am I understanding this correctly?

**Comment by jfrazelle** [comment]
yup yup :) and if you are interested I wrote a blog on runc+userns, doesnt
have much to do with the docker implementation but still cool ;)

On Wed, Feb 17, 2016 at 8:03 AM, Etienne Bruines <notifications@github.com>
wrote:

> That just blew my mind away. (Thank you for the reference!) According to
> the release blog
> <https://blog.docker.com/2016/02/docker-engine-1-10-security/>, all I
> have to do is run docker with the --userns-remap, without changes to the
> container / run command.
>
> Am I understanding this correctly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/114#issuecomment-185272393>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by EtienneBruines** [comment]
I'm assuming it's [this one](https://blog.jessfraz.com/post/runc-containers-on-the-desktop/) (also for future readers of this issue). 

Thank you very much. Still stuck on the issue described in #65, but that's unrelated to this one. (I think this one can be closed. )

**Comment by jfrazelle** [comment]
You will need to compile your kernel with userns I bet

On Wednesday, February 17, 2016, Etienne Bruines <notifications@github.com>
wrote:

> I'm assuming it's this one
> <https://blog.jessfraz.com/post/runc-containers-on-the-desktop/> (also
> for future readers of this issue).
>
> Thank you very much. Still stuck on the issue described in #65
> <https://github.com/jfrazelle/dockerfiles/issues/65>, but that's
> unrelated to this one. (I think this one can be closed. )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/114#issuecomment-185278237>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by EtienneBruines** [comment]
I am afraid so (not running Arch, but Debian; a bit less documentation on that). I do wonder why this isn't enabled by-default (or by kernel boot parameter), even with the newer kernels (running 4.3.0 now).

**Comment by jfrazelle** [comment]
https://github.com/jfrazelle/dockerfiles/issues/65 Closing Same as
