### ISSUE TITLE
DISPLAY for ssh session with X-forwarding

### ISSUE THREAD

**Issue by EderSantana** [jfrazelle/dockerfiles#129]
Hi, thanks for the dockerfiles!

I'm trying to test the atom dockerfile in an ssh session. The server got the image configured but running:

`docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY atom`

returns:

```
18:0422/154056:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[18:0422/154056:ERROR:browser_main_loop.cc(253)] Gtk: cannot open display: unixlocalhost:10.0
```

Is there anything else I could do in that case?

**Comment by jfrazelle** [comment]
Your display variable looks wrong

**Comment by jfrazelle** [comment]
you are in an ssh session, there is no display, you are headless
