### ISSUE TITLE
Various Issues on Ubuntu 16.04 with Docker 1.11.x

### ISSUE THREAD

**Issue by pryorda** [jfrazelle/dockerfiles#135]
Do you think its worth adding xhost local: to the instructions for all X based images?

Thanks,
Dan

**Comment by jfrazelle** [comment]
Depends on distro it's kinda redundant

On Friday, April 29, 2016, Daniel Pryor <notifications@github.com> wrote:

> Do you think its worth adding xhost local: to the instructions for all X
> based images?
>
> Thanks,
> Dan
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/135>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by pryorda** [comment]
Yeah, I'm noticing some weirdness with stuff on Ubuntu 16.04, 4.4 kernel, and docker 1.11.1. We will see what I can figure out and Ill post various hacks I had to do here to get things working.

**Comment by pryorda** [comment]
Had to download your [chrome seccomp profile](https://github.com/jfrazelle/dotfiles/blob/master/etc/docker/seccomp/chrome.json) for chrome and add it to the CWD (i.e dockerfiles/chrome/stable)

We also need to add installing libexif12  to your Dockerfile, unless there is a reason you left it out. 

Then I wrote this start.sh script that others might find a use for. 

```
#!/bin/bash

CHROME_DATA_DIR="${HOME}"/.docker-google-chrome/
DOWNLOAD_DIR="${HOME}"/Downloads

if [ ! `xhost |grep -c LOCAL` -ge 1 ]
then
    echo "adding local permissions to X socket"
    xhost local:
fi

# Check for local image otherwise pull 
if [ `docker images |grep -c chrome` -ge 1 ] 
then
    DOCKER_CHROME_IMAGE=`docker images | grep chrome |head -n 1 |awk '{print $1}'`
else
    DOCKER_CHROME_IMAGE="jess/chrome"
fi


docker run --rm -it \
	--security-opt seccomp:./chrome-seccomp.json \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY=unix"${DISPLAY}" \
        -v "${DOWNLOAD_DIR}":/root/Downloads \
	-v "${CHROME_DATA_DIR}":/data \
	--device /dev/snd \
        --name chrome \
	"${DOCKER_CHROME_IMAGE}"
```
