### ISSUE TITLE
.X11-unix Synology

### ISSUE THREAD

**Issue by walkertron** [jfrazelle/dockerfiles#140]
Hey there, 

Try to run tor-browser on Docker for Synology. SSH'd to the machine and ran the commands

_docker run -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -e DISPLAY=unix$DISPLAY jess/tor-browser_

But getting this issue 

_Error response from daemon: Cannot start container 569cbe3a00c03925cd700d45c5144d2d250ea86867104279792c7870c09b883c: stat /tmp/.X11-unix: no such file or directory_

Perhaps this is a noob issue, but I don't know how to sort this?

Thanks

**Comment by jfrazelle** [comment]
Your NAS doesn't have X11 it's headless ;)






On Tue, May 17, 2016 at 2:02 AM -0700, "walkertron" <notifications@github.com> wrote:












Hey there, 



Try to run tor-browser on Docker for Synology. SSH'd to the machine and ran the commands



docker run -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/snd:/dev/snd -e DISPLAY=unix$DISPLAY jess/tor-browser



But getting this issue 



Error response from daemon: Cannot start container 569cbe3a00c03925cd700d45c5144d2d250ea86867104279792c7870c09b883c: stat /tmp/.X11-unix: no such file or directory



Perhaps this is a noob issue, but I don't know how to sort this?



Thanks
