### ISSUE TITLE
Chrome won't work without --no-sandbox option

### ISSUE THREAD

**Issue by mosajjal** [jfrazelle/dockerfiles#149]
Hi ! 

I'm using Arch as host, with 4.6.2-1 kernel and 1.11.2 is my Docker version.

This doesn't work for me:

```
 docker run -it \
	--net host \ # may as well YOLO
	--cpuset-cpus 0 \ # control the cpu
	--memory 512mb \ # max memory it can use
	-v /tmp/.X11-unix:/tmp/.X11-unix \ # mount the X11 socket
	-e DISPLAY=unix$DISPLAY \
	-v $HOME/Downloads:/root/Downloads \
	-v $HOME/.config/google-chrome/:/data \ # if you want to save state
	--device /dev/snd \ # so we have sound
	-v /dev/shm:/dev/shm \
	--name chrome \
	jess/chrome
```

this doesn't open the chrome window for me. but when I add` --no-sandbox` or `--disable-setuid-sandbox`, it works. 

Also, with 512mb ram, it crashes tabs multiple times, also "HTTPS everywhere" and "uBlock" will crash multiple times. adding `--disable-appcontainer` won't help either. 

is there any way to run Chrome container with sand-boxing in Arch ?

best regards.

**Comment by jfrazelle** [comment]
Oh it's because you don't have userns enabled in your kernel

**Comment by jfrazelle** [comment]
See https://github.com/jfrazelle/dockerfiles/issues/65

**Comment by mosajjal** [comment]
I can confirm after enabling User Namespace and re-compiling the kernel (4.7RC3), it works flawlessly. Also, VLC on docker seems to be working better and i3 shows the logo at the bottom.

**Comment by creatist** [comment]
I got the same problem ,so i disable sandbox ,but it still cann't works!

**Comment by koep** [comment]
@creatist You need to enable user namespaces in your kernel for this to work.

**Comment by quldude** [comment]
> I can confirm after enabling User Namespace and re-compiling the kernel (4.7RC3), it works flawlessly. Also, VLC on docker seems to be working better and i3 shows the logo at the bottom.

Could you tell me what command you ran to do this? I'm new to docker.

**Comment by kevhill** [comment]
For anyone looking for a bit more help about user namespaces in docker:
[Introduction to User Namespaces in Docker Engine](https://success.docker.com/article/introduction-to-user-namespaces-in-docker-engine)

You can also set this in a [daemon configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file), but it doesn't seem to be an available option on docker for Windows, which is where I am currently trying to run a puppeteer app... fml

**Comment by pranav083** [comment]
> > I can confirm after enabling User Namespace and re-compiling the kernel (4.7RC3), it works flawlessly. Also, VLC on docker seems to be working better and i3 shows the logo at the bottom.
> 
> Could you tell me what command you ran to do this? I'm new to docker.

did you get any resources for how to disable sandbox and run chrome in docker.

**Comment by dbolser** [comment]
> > > I can confirm after enabling User Namespace and re-compiling the kernel (4.7RC3), it works flawlessly. Also, VLC on docker seems to be working better and i3 shows the logo at the bottom.
> > 
> > 
> > Could you tell me what command you ran to do this? I'm new to docker.
> 
> did you get any resources for how to disable sandbox and run chrome in docker.

Yes, please help! I'm totally lost reading pages like this:
https://docs.docker.com/engine/security/userns-remap/
