### ISSUE TITLE
r.j3ss.co needs a new Let's Encrypt cert

### ISSUE THREAD

**Issue by koep** [jfrazelle/dockerfiles#159]
Hi @jfrazelle 
```
docker: Error response from daemon: Get https://r.j3ss.co/v1/_ping: x509: certificate has expired or is not yet valid.
```
Just saying!

**Comment by jfrazelle** [comment]
ah good find ill update it

On Wed, Jun 29, 2016 at 7:48 AM, Christian <notifications@github.com> wrote:

> Hi,
>
> docker: Error response from daemon: Get https://r.j3ss.co/v1/_ping: x509: certificate has expired or is not yet valid.
>
> Just saying!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/159>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbElfnrureFnBWZpKpaI7ZfVj5H80ks5qQoWogaJpZM4JBNwJ>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
done

On Wed, Jun 29, 2016 at 3:23 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> ah good find ill update it
>
> On Wed, Jun 29, 2016 at 7:48 AM, Christian <notifications@github.com>
> wrote:
>
>> Hi,
>>
>> docker: Error response from daemon: Get https://r.j3ss.co/v1/_ping: x509: certificate has expired or is not yet valid.
>>
>> Just saying!
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/159>, or mute the thread
>> <https://github.com/notifications/unsubscribe/ABYNbElfnrureFnBWZpKpaI7ZfVj5H80ks5qQoWogaJpZM4JBNwJ>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by koep** [comment]
thanks!

**Comment by mosajjal** [comment]
https://www.startssl.com/

this one gives longer certs for free. it has a 39 month cert. if we're not automating the SSL, better use a longer one, right ?

**Comment by jfrazelle** [comment]
I'm automating it now ;)

On Wednesday, June 29, 2016, Alireza Mosajjal <notifications@github.com>
wrote:

> https://www.startssl.com/
>
> this one gives longer certs for free. it has a 39 month cert. if we're not
> automating the SSL, better use a longer one, right ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/159#issuecomment-229563807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbCqmRsmW5Y8HM6_43l7KkQli0RhAks5qQ1XugaJpZM4JBNwJ>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by mosajjal** [comment]
great !

**Comment by koep** [comment]
Will you use certbot in a container to automate it?
It would be cool to know how you do it!

I'm currently doing it myself by using certbot in a container (keeping it running with an infinite loop) and doing "docker exec certbot certbot renew" via cron. I'm not sure if this is the most elegant way

**Comment by jfrazelle** [comment]
Ha ya that's basically it

On Wednesday, June 29, 2016, Christian <notifications@github.com> wrote:

> Will you use certbot in a container to automate it?
> It would be cool to know how you do it!
>
> I'm currently doing it myself by using certbot in a container (keeping it
> running with an infinite loop) and doing "docker exec certbot certbot
> renew" via cron. I'm not sure if this is the most elegant way
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/159#issuecomment-229567550>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbKmGvEGILX2hY_VtpGpHOPdAKqDkks5qQ1y7gaJpZM4JBNwJ>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
