### ISSUE TITLE
Virtualbox on docker

### ISSUE THREAD

**Issue by Nasjoe** [jfrazelle/dockerfiles#18]
Hi Jess ! Thank you for your all repository.
I'm trying your virtualbox docker file, but i got this error :

WARNING: The character device /dev/vboxdrv does not exist. Try
           sudo /etc/init.d/vboxdrv restart
         and if that is not successful, try to re-install the package.
         You will not be able to start VMs until this problem is fixed.

I think that The virtualbox driver device must be mounted from host.
Maybe we have to add within the builfile this :

VOLUME /dev/vboxdrv

But don't work too.
I'm still searching :)

**Comment by Nasjoe** [comment]
maybe the same error here :
https://github.com/Jencryzthers/VboxInsideDocker/issues/4

**Comment by jfrazelle** [comment]
This one is special it takes some love on your kernel as well to work I'll
work on documenting it

On Friday, May 8, 2015, Jonas <notifications@github.com> wrote:

> maybe the same error here :
> Jencryzthers/VboxInsideDocker#4
> <https://github.com/Jencryzthers/VboxInsideDocker/issues/4>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/18#issuecomment-100392349>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
added https://github.com/jfrazelle/dockerfiles/blob/master/virtualbox/Dockerfile#L10
