### ISSUE TITLE
starting jess/deb-dev gives "cannot execute binary file"

### ISSUE THREAD

**Issue by tarand** [jfrazelle/dockerfiles#182]
I just tried to start the deb-dev container on my Windows 10 host.
First of all: The Dockerfile of it does not have a "usage" section. Please add...
Second: I tried to start it using 
     docker run -it jess/deb-dev /bin/bash

But that gives:

Unable to find image 'jess/deb-dev:latest' locally
latest: Pulling from jess/deb-dev

03e1855d4f31: Pull complete
a3ed95caeb02: Pull complete
4eb3f3101d70: Pull complete
3d01462bf1eb: Pull complete
7a57199b9e7e: Pull complete
Digest: sha256:80245dda824f49dcd30acd7e241f2b0c9137a110e7af7870197934d21e58feda
Status: Downloaded newer image for jess/deb-dev:latest
/bin/bash: /bin/bash: cannot execute binary file
PS C:\Users\tarand\Documents\Einarbeitung\docker\devenv>

**Comment by koep** [comment]
try ```docker run -it jess/deb-dev```

**Comment by tarand** [comment]
Hi, thanks a lot, it works...
