### ISSUE TITLE
/dev/snd not accessible for spotify

### ISSUE THREAD

**Issue by fkautz** [jfrazelle/dockerfiles#26]
I get this nice little error message when attempting to run spotify on a 15.04 system:

```
FATA[0000] Error response from daemon: Cannot start container 05b351ea134e190cb09465658c2b50f5880be3184bfc2ee7a17797ec2a7319da: error gathering device information while adding custom device "/dev/snd": not a device node 
```

Any advice on how to fix this? :)

**Comment by jfrazelle** [comment]
you can use docker 1.7.0 its on test.docker.com it has a patch to mount
device nodes recursively if a folder is given

On Mon, Jun 15, 2015 at 7:21 PM, Frederick F. Kautz IV <
notifications@github.com> wrote:

> I get this nice little error message when attempting to run spotify on a
> 15.04 system:
>
> ```FATA[0000] Error response from daemon: Cannot start container
> 05b351ea134e190cb09465658c2b50f5880be3184bfc2ee7a17797ec2a7319da: error
> gathering device information while adding custom device "/dev/snd": not a
> device node
>
>
> Any advice on how to fix this? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/26>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by fkautz** [comment]
Thanks, solved the first problem. 

Getting this now:
```
(spotify:1): Gtk-WARNING **: cannot open display: unix:0
```

```
$ echo $DISPLAY
:0
```

**Comment by fkautz** [comment]
BTW, i'll add all this into a readme and submit it back. :)

**Comment by jfrazelle** [comment]
are u on a mac?

On Mon, Jun 15, 2015 at 7:41 PM, Frederick F. Kautz IV <
notifications@github.com> wrote:

> BTW, i'll add all this into a readme and submit it back. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/26#issuecomment-112264134>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
xhost local:root, if u are on linux, on a mac u need to follow the ac
instructions

On Mon, Jun 15, 2015 at 7:44 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> are u on a mac?
>
> On Mon, Jun 15, 2015 at 7:41 PM, Frederick F. Kautz IV <
> notifications@github.com> wrote:
>
>> BTW, i'll add all this into a readme and submit it back. :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/26#issuecomment-112264134>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by fkautz** [comment]
I was able to start up the app, receiving this:

```
02:53:04.680 I [head_file_streamer.cpp:106      ] Requesting head file from CDN url: http://heads-fa.spotify.com/head/159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e 
02:53:04.680 D [spirc_manager.cpp:710           ] GAIA: SpircManager::stpLoad, track=spotify:track:2XtVPjmDvtm1dGtTYW5Pct, index=2, position=0, paused=0
02:53:04.680 D [spirc_manager.cpp:1883          ] GAIA: SpircManager::becomeActiveDevice
02:53:04.680 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95893090
02:53:04.680 I [ap_chunk_downloader.cpp:75      ] Requesting data (0 -> 524288) from AP for file 159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e
02:53:04.681 I [sliding_window_prefetch_strategy.cpp:333] Prefetch: looks like a skip or partial context change - halving window size to 1
02:53:04.681 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95893089
02:53:04.719 I [cdn_chunk_downloader.cpp:72     ] Requesting data (0 -> 524288) from CDN url: http://audio-fa.spotify.com/audio/159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e?fBSMe25sWM6lR2SL9hgfpkt3MhUbRoaRd9Y5iI+Zh0c= 
02:53:05.000 I [http_fetch_connection.cpp:376   ] Result 206 Partial Content
02:53:05.065 E [audio_decompressor_process.cpp:379] playbackError(-2)
02:53:06.043 D [spirc_manager.cpp:710           ] GAIA: SpircManager::stpLoad, track=spotify:track:2XtVPjmDvtm1dGtTYW5Pct, index=2, position=0, paused=0
02:53:06.043 D [spirc_manager.cpp:1883          ] GAIA: SpircManager::becomeActiveDevice
02:53:06.043 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95891728
02:53:06.043 E [audio_decompressor_process.cpp:379] playbackError(-2)
02:53:06.044 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95891726
02:53:06.045 I [ap_chunk_downloader.cpp:75      ] Requesting data (131072 -> 655360) from AP for file 159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e
```

and an error message in the UI claiming it cannot download from the internet due to network configuration issues.

**Comment by jfrazelle** [comment]
hmmm idk i have nevr seen that what os are u running, like i said in my
talk a lot of the problems u see in containers are the same as on a host
maybe try execinng in and pinging something, ya know

On Mon, Jun 15, 2015 at 8:01 PM, Frederick F. Kautz IV <
notifications@github.com> wrote:

> I was able to start up the app, receiving this:
>
> 02:53:04.680 I [head_file_streamer.cpp:106      ] Requesting head file from CDN url: http://heads-fa.spotify.com/head/159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e
> 02:53:04.680 D [spirc_manager.cpp:710           ] GAIA: SpircManager::stpLoad, track=spotify:track:2XtVPjmDvtm1dGtTYW5Pct, index=2, position=0, paused=0
> 02:53:04.680 D [spirc_manager.cpp:1883          ] GAIA: SpircManager::becomeActiveDevice
> 02:53:04.680 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95893090
> 02:53:04.680 I [ap_chunk_downloader.cpp:75      ] Requesting data (0 -> 524288) from AP for file 159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e
> 02:53:04.681 I [sliding_window_prefetch_strategy.cpp:333] Prefetch: looks like a skip or partial context change - halving window size to 1
> 02:53:04.681 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95893089
> 02:53:04.719 I [cdn_chunk_downloader.cpp:72     ] Requesting data (0 -> 524288) from CDN url: http://audio-fa.spotify.com/audio/159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e?fBSMe25sWM6lR2SL9hgfpkt3MhUbRoaRd9Y5iI+Zh0c=
> 02:53:05.000 I [http_fetch_connection.cpp:376   ] Result 206 Partial Content
> 02:53:05.065 E [audio_decompressor_process.cpp:379] playbackError(-2)
> 02:53:06.043 D [spirc_manager.cpp:710           ] GAIA: SpircManager::stpLoad, track=spotify:track:2XtVPjmDvtm1dGtTYW5Pct, index=2, position=0, paused=0
> 02:53:06.043 D [spirc_manager.cpp:1883          ] GAIA: SpircManager::becomeActiveDevice
> 02:53:06.043 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95891728
> 02:53:06.043 E [audio_decompressor_process.cpp:379] playbackError(-2)
> 02:53:06.044 D [spirc_manager.cpp:668           ] GAIA:   current state ID updated to -95891726
> 02:53:06.045 I [ap_chunk_downloader.cpp:75      ] Requesting data (131072 -> 655360) from AP for file 159aab01f01b0ce6fbc494f2cd4754ca9ab80a1e
>
> and an error message in the UI claiming it cannot download from the
> internet due to network configuration issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/26#issuecomment-112266976>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by fkautz** [comment]
On ubuntu 15.04, latest version of what is published on test. What's interesting is it lets me log in, browse music, see my playlists, and refuses to download music. :(

**Comment by jfrazelle** [comment]
Seems suspicious I use this image everyday on Debian

On Monday, June 15, 2015, Frederick F. Kautz IV <notifications@github.com>
wrote:

> On ubuntu 15.04, latest version of what is published on test. What's
> interesting is it lets me log in, browse music, see my playlists, and
> refuses to download music. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/26#issuecomment-112270537>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Maybe spotify bug? Is there anything in dmesg?

**Comment by fkautz** [comment]
Here is what I get from dmesg:

```
[72754.411042] aufs au_opts_verify:1612:docker[2584]: dirperm1 breaks the protection by the permission bits on the lower branch
[72754.435734] aufs au_opts_verify:1612:docker[2584]: dirperm1 breaks the protection by the permission bits on the lower branch
[72754.451601] aufs au_opts_verify:1612:docker[2582]: dirperm1 breaks the protection by the permission bits on the lower branch
[72754.453327] IPv6: ADDRCONF(NETDEV_UP): vethd5011f1: link is not ready
[72754.453803] IPv6: ADDRCONF(NETDEV_CHANGE): vethd5011f1: link becomes ready
[72754.454161] device vethd5011f1 entered promiscuous mode
[72754.454287] docker0: port 1(vethd5011f1) entered forwarding state
[72754.454302] docker0: port 1(vethd5011f1) entered forwarding state
[72754.517889] eth0: renamed from vethc32e337
[72769.495491] docker0: port 1(vethd5011f1) entered forwarding state
[72773.612738] audit: type=1400 audit(1434840973.591:41): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.612838] audit: type=1400 audit(1434840973.591:42): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.613037] audit: type=1400 audit(1434840973.591:43): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.613120] audit: type=1400 audit(1434840973.591:44): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.616668] audit: type=1400 audit(1434840973.595:45): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.616878] audit: type=1400 audit(1434840973.595:46): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.997333] audit: type=1400 audit(1434840973.979:47): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
[72773.997436] audit: type=1400 audit(1434840973.979:48): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=2735 comm="Chrome_IOThread" requested_mask="trace" denied_mask="trace" peer="docker-default"
```

The apparmor="DENIED" messages floods dmesg (lots of suppressed repeats) until I kill the app.

**Comment by fkautz** [comment]
Interestingly, the spotify app properly acts as a remote control for my phone. ;) Even that alone is useful for me.

**Comment by jfrazelle** [comment]
I figured it out.... its pulseaudio.... and idk how to stop it, but i run pulseaudio in a container and noticed it on another persons computer w pulseaudio on their host, removing pulseaudio fixed the problem.... i have no idea

**Comment by evermax** [comment]
Sorry to reopen this thread, but I have a question about it. @jfrazelle you mention here:
> on a mac u need to follow the mac instructions
To which instructions do you refer to? I am trying to find how to have the sound on Mac OS from a Docker container, but I can't find the info..

**Comment by Joshfindit** [comment]
This may be necroing, but this issue came up in a Google search for `/dev/snd` on MacOS.

`/dev/snd/` is created mainly by ALSA, which does not run on OSX. JACK may also create these and MAY run on OSX, but the essential issue for docker containers on Mac is that the exposed sound systems are totally different.

There is some work around using pulseaudio (mainly by relaying the sound from the container to the host over tcp), but that does not feel like a nice solid and stable solution.

**Comment by mathfeola** [comment]
@Joshfindit Thanks for the info! Still looking for a way to run the client through docker...
