### ISSUE TITLE
2 questions about running atom on docker

### ISSUE THREAD

**Issue by pdhoward** [jfrazelle/dockerfiles#30]
These dockerfiles are very helpful!

I am a bit of newbie on docker -- but I hope you can point me in the right
direction if you can't answer this question directly.

1. I successfully launched Atom in the docker container -- after running the
command xhost + on my local ubuntu host --- works great!

If I wanted to reach this container from my Windows platform and run Atom as
a remote gui app -- what would I need to do?

2. I noticed that the files in Atom were not persistent. Any suggestions on
how to make these persistent using the local file system in the Container?

**Comment by jfrazelle** [comment]
You could use a volume for files

Wrt windows there is no way currently
