### ISSUE TITLE
Pixel ratio / QT size in X11 apps

### ISSUE THREAD

**Issue by charliedrage** [jfrazelle/dockerfiles#31]
First things first, awesome job FYI. Love throwing desktop apps into docker.

Everything works great and I've even got Hipchat running throught X11. Just one thing left that's been bothering me, hiDPI.

docker run --rm -it -v /etc/machine-id:/etc/machine-id:ro \
-v /etc/localtime:/etc/localtime:ro \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e DISPLAY=unix$DISPLAY\
 --device /dev/snd \
-v /var/run/dbus:/var/run/dbus \
-e GDK_SCALE \
-e GDK_DPI_SCALE \
-e QT_DEVICE_PIXEL_RATIO\
 --name hipchat hipchat

But no matter what I do, it doesn't scale. In QT or GDK. I've Google'd for hours and troubleshooted and I've came here as a last resort.

FYI, I'm running Debian 8 with Gnome3 and the GDK_SCALE values, etc, are in my .zshrc + .bashrc

Any ideas what I may be missing?

**Comment by jfrazelle** [comment]
idk, it is something with the app
