### ISSUE TITLE
starting visual studio container: error gathering device information while adding custom device "/dev/dri": not a device node 

### ISSUE THREAD

**Issue by miqui** [jfrazelle/dockerfiles#34]
docker run -d -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/dri --name visualstudio jess/visualstudio
Unable to find image 'jess/visualstudio:latest' locally
latest: Pulling from jess/visualstudio
5385af2045ef: Pull complete 
8e7f55543130: Pull complete 
b7868c184c2f: Pull complete 
3c63844759ef: Pull complete 
00cc8e506cb0: Pull complete 
67d87eb55e1b: Pull complete 
cc4982629f83: Pull complete 
8d6b3651744e: Pull complete 
c818e0a83cf4: Pull complete 
0e57ef9cf1ca: Pull complete 
f9914c2bee3b: Pull complete 
2c98714cd135: Pull complete 
4723c1eafa97: Pull complete 
4186e6387c9f: Pull complete 
552ca6a9a1b4: Pull complete 
6fac5857b266: Pull complete 
19ab81b3cf7a: Already exists 
Digest: sha256:459df677cbfc29c3ef379050dba34747213c5ccaa81827977bfebbac9abd53bd
Status: Downloaded newer image for jess/visualstudio:latest
a099691d3f4969eccc94e2c9bbc5392d4b08c1f5d5c04d3ca3f4f01020fe18c6
FATA[0125] Error response from daemon: Cannot start container a099691d3f4969eccc94e2c9bbc5392d4b08c1f5d5c04d3ca3f4f01020fe18c6: error gathering device information while adding custom device "/dev/dri": not a device node

**Comment by koep** [comment]
What version of docker are you running? I believe this was fixed in 1.7.

**Comment by miqui** [comment]
am using 1.6.2

**Comment by jfrazelle** [comment]
you need 1.7 for --device to work recurisively, it was a patch i made

**Comment by miqui** [comment]
indeed with 1.7 it worked...
