### ISSUE TITLE
trying to start pulseaudio container on ubuntu 14.04 failed 

### ISSUE THREAD

**Issue by xinity** [jfrazelle/dockerfiles#38]
hi,

i'm trying to get pulseaudio working on my fresh ubuntu 14.04 install, but start fails with strange error:
I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
I: [pulseaudio] core-util.c: Failed to acquire high-priority scheduling: Input/output error
I: [pulseaudio] main.c: This is PulseAudio 6.0
D: [pulseaudio] main.c: Compilation host: x86_64-pc-linux-gnu
D: [pulseaudio] main.c: Compilation CFLAGS: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wextra -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -ffast-math -fno-common -fdiagnostics-show-option -fdiagnostics-color=auto
D: [pulseaudio] main.c: Running on host: Linux x86_64 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015
D: [pulseaudio] main.c: Found 4 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: FASTPATH defined, only fast path asserts disabled.
I: [pulseaudio] main.c: Machine ID is c13e7e2624cc4eb7979db4ae87de51f9.
I: [pulseaudio] main.c: Using runtime directory /home/pulseaudio/.config/pulse/c13e7e2624cc4eb7979db4ae87de51f9-runtime.
I: [pulseaudio] main.c: Using state directory /home/pulseaudio/.config/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-6.0/modules.
I: [pulseaudio] main.c: Running in system mode: no
I: [pulseaudio] main.c: Fresh high-resolution timers available! Bon appetit!
D: [pulseaudio] memblock.c: Using shared memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65472
D: [pulseaudio] memblock.c: Using shared memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65472
I: [pulseaudio] cpu-x86.c: CPU flags: CMOV MMX SSE SSE2 SSE3 SSSE3 SSE4_1 SSE4_2 
I: [pulseaudio] svolume_mmx.c: Initialising MMX optimized volume functions.
I: [pulseaudio] remap_mmx.c: Initialising MMX optimized remappers.
I: [pulseaudio] svolume_sse.c: Initialising SSE2 optimized volume functions.
I: [pulseaudio] remap_sse.c: Initialising SSE2 optimized remappers.
I: [pulseaudio] sconv_sse.c: Initialising SSE2 optimized conversions.
I: [pulseaudio] svolume_orc.c: Initialising ORC optimized volume functions.
D: [pulseaudio] alsa-util.c: Trying default with SND_PCM_NO_AUTO_FORMAT ...
I: [pulseaudio] (alsa-lib)pcm_hw.c: open '/dev/snd/pcmC0D0c' failed (-2)
I: [pulseaudio] (alsa-lib)pcm_dsnoop.c: unable to open slave
I: [pulseaudio] alsa-util.c: Error opening PCM device default: No such file or directory
E: [pulseaudio] module.c: Failed to load module "module-alsa-source" (argument: "device="default" tsched=1"): initialization failed.
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.
I: [pulseaudio] main.c: Daemon terminated

and container keep restarting over and over :(

did i miss something ?

thanks a lot for your awesome container work !

**Comment by jfrazelle** [comment]
If you are running Ubuntu it's probably already running pulseaudio on your
host

On Tuesday, July 7, 2015, xinity <notifications@github.com> wrote:

> hi,
>
> i'm trying to get pulseaudio working on my fresh ubuntu 14.04 install, but
> start fails with strange error:
> I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation
> not permitted
> I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation
> not permitted
> D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to
> connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> I: [pulseaudio] core-util.c: Failed to acquire high-priority scheduling:
> Input/output error
> I: [pulseaudio] main.c: This is PulseAudio 6.0
> D: [pulseaudio] main.c: Compilation host: x86_64-pc-linux-gnu
> D: [pulseaudio] main.c: Compilation CFLAGS: -g -O2
> -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wextra
> -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations
> -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security
> -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self
> -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes
> -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow
> -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings
> -Wno-unused-parameter -ffast-math -fno-common -fdiagnostics-show-option
> -fdiagnostics-color=auto
> D: [pulseaudio] main.c: Running on host: Linux x86_64 3.16.0-41-generic
> #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015
> D: [pulseaudio] main.c: Found 4 CPUs.
> I: [pulseaudio] main.c: Page size is 4096 bytes
> D: [pulseaudio] main.c: Compiled with Valgrind support: no
> D: [pulseaudio] main.c: Running in valgrind mode: no
> D: [pulseaudio] main.c: Running in VM: no
> D: [pulseaudio] main.c: Optimized build: yes
> D: [pulseaudio] main.c: FASTPATH defined, only fast path asserts disabled.
> I: [pulseaudio] main.c: Machine ID is c13e7e2624cc4eb7979db4ae87de51f9.
> I: [pulseaudio] main.c: Using runtime directory
> /home/pulseaudio/.config/pulse/c13e7e2624cc4eb7979db4ae87de51f9-runtime.
> I: [pulseaudio] main.c: Using state directory
> /home/pulseaudio/.config/pulse.
> I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-6.0/modules.
> I: [pulseaudio] main.c: Running in system mode: no
> I: [pulseaudio] main.c: Fresh high-resolution timers available! Bon
> appetit!
> D: [pulseaudio] memblock.c: Using shared memory pool with 1024 slots of
> size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is
> 65472
> D: [pulseaudio] memblock.c: Using shared memory pool with 1024 slots of
> size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is
> 65472
> I: [pulseaudio] cpu-x86.c: CPU flags: CMOV MMX SSE SSE2 SSE3 SSSE3 SSE4_1
> SSE4_2
> I: [pulseaudio] svolume_mmx.c: Initialising MMX optimized volume functions.
> I: [pulseaudio] remap_mmx.c: Initialising MMX optimized remappers.
> I: [pulseaudio] svolume_sse.c: Initialising SSE2 optimized volume
> functions.
> I: [pulseaudio] remap_sse.c: Initialising SSE2 optimized remappers.
> I: [pulseaudio] sconv_sse.c: Initialising SSE2 optimized conversions.
> I: [pulseaudio] svolume_orc.c: Initialising ORC optimized volume functions.
> D: [pulseaudio] alsa-util.c: Trying default with SND_PCM_NO_AUTO_FORMAT ...
> I: pulseaudio <http://alsa-lib>pcm_hw.c: open '/dev/snd/pcmC0D0c' failed
> (-2)
> I: pulseaudio <http://alsa-lib>pcm_dsnoop.c: unable to open slave
> I: [pulseaudio] alsa-util.c: Error opening PCM device default: No such
> file or directory
> E: [pulseaudio] module.c: Failed to load module "module-alsa-source"
> (argument: "device="default" tsched=1"): initialization failed.
> E: [pulseaudio] main.c: Module load failed.
> E: [pulseaudio] main.c: Failed to initialize daemon.
> I: [pulseaudio] main.c: Daemon terminated
>
> and container keep restarting over and over :(
>
> did i miss something ?
>
> thanks a lot for your awesome container work !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/38>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by xinity** [comment]
indeed!
Should i adapt my host config to make skype/spotify containers able to communicate with pulseaudio ?

**Comment by jfrazelle** [comment]
Yes

On Tuesday, July 7, 2015, xinity <notifications@github.com> wrote:

> indeed!
> Should i adapt my host config to make skype/spotify containers able to
> communicate with pulseaudio ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/38#issuecomment-119241607>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by xinity** [comment]
awesome !!!
it' works like a charm, 

thanks a lot :)

**Comment by senrabdet** [comment]
Hi jess - I reiterate how great your container work is!  Am having same trouble as xinity, and am unclear how it was solved.  I'm trying to get the Tor and pulseaudio containers to link (in virtualbox Centos 7 VMs).   I think pulseaudio is crashing with same errors shown above.  Did solution " adapt my host config" mean changing the "HostConfig object" and is there a URL you could suggest on how to do this?  Does this introduce security issues?  I'm using Docker 1.8.3.  Thanks!

**Comment by jfrazelle** [comment]
Either uninstall pulse audio on your host or set your host pulse audio to run on the port specified in my container you can't have 2 pulse audios running

**Comment by senrabdet** [comment]
Thanks Jess, you're the best!

Ted Barnes
Soholistic Networks
www.soholistic.net
(508) 277 9666

**Comment by senrabdet** [comment]
Hi Jess:

Sorry to ask, but am still having trouble getting sound to work and was hoping you might have a suggestion or two.  Again, I'm running docker 1.8.3 inside of virtualbox 5.0.4 on Windows 10....

I spun up a new virtualbox vm (jessie) with a minimal mate desktop, and did a "apt-get autoremove pulseaudio".  A dpkg-query -l 'pulse*' shows (so I think pulseaudio is uninstalled on the vm):
"un  pulseaudio                  <none>             <none>             (no description available)"

Your spotify and linked pulseaudio/tor containers all see to start and run fine without errors but also with no sound (i.e., first trying spotify, then trying linked pulseaudio/tor).

Q:  with pulseaudio gone, do I need some sort of sound on virtualbox like alsa?  Or is it possible there's still some remnant on the vm?
Q:  it the problem with my using windows 10?
Q:  are there other errors I can look for to try to troubleshoot this?

Stumped!  Any thoughts appreciated...Best,  Ted

**Comment by jfrazelle** [comment]
yes alsa for sure

On Tue, Nov 3, 2015 at 9:37 AM, senrabdet <notifications@github.com> wrote:

> Hi Jess:
>
> Sorry to ask, but am still having trouble getting sound to work and was
> hoping you might have a suggestion or two. Again, I'm running docker 1.8.3
> inside of virtualbox 5.0.4 on Windows 10....
>
> I spun up a new virtualbox vm (jessie) with a minimal mate desktop, and
> did a "apt-get autoremove pulseaudio". A dpkg-query -l 'pulse*' shows (so I
> think pulseaudio is uninstalled on the vm):
> "un pulseaudio (no description available)"
>
> Your spotify and linked pulseaudio/tor containers all see to start and run
> fine without errors but also with no sound (i.e., first trying spotify,
> then trying linked pulseaudio/tor).
>
> Q: with pulseaudio gone, do I need some sort of sound on virtualbox like
> alsa? Or is it possible there's still some remnant on the vm?
> Q: it the problem with my using windows 10?
> Q: are there other errors I can look for to try to troubleshoot this?
>
> Stumped! Any thoughts appreciated...Best, Ted
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/38#issuecomment-153427933>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
i have no tried these on ubuntu so I am unsure if they work :/ the
virtualbox should not be an issue unless you are running in headless mode

On Tue, Nov 3, 2015 at 9:45 AM, Jessica Frazelle <me@jessfraz.com> wrote:

> yes alsa for sure
>
> On Tue, Nov 3, 2015 at 9:37 AM, senrabdet <notifications@github.com>
> wrote:
>
>> Hi Jess:
>>
>> Sorry to ask, but am still having trouble getting sound to work and was
>> hoping you might have a suggestion or two. Again, I'm running docker 1.8.3
>> inside of virtualbox 5.0.4 on Windows 10....
>>
>> I spun up a new virtualbox vm (jessie) with a minimal mate desktop, and
>> did a "apt-get autoremove pulseaudio". A dpkg-query -l 'pulse*' shows (so I
>> think pulseaudio is uninstalled on the vm):
>> "un pulseaudio (no description available)"
>>
>> Your spotify and linked pulseaudio/tor containers all see to start and
>> run fine without errors but also with no sound (i.e., first trying spotify,
>> then trying linked pulseaudio/tor).
>>
>> Q: with pulseaudio gone, do I need some sort of sound on virtualbox like
>> alsa? Or is it possible there's still some remnant on the vm?
>> Q: it the problem with my using windows 10?
>> Q: are there other errors I can look for to try to troubleshoot this?
>>
>> Stumped! Any thoughts appreciated...Best, Ted
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/38#issuecomment-153427933>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
Thanks(!)...will try, post back (appreciate your help)

**Comment by benileo** [comment]
For anyone still having this issue, find the location of the unix domain socket on your host `$ netstat -lnp | grep "pulseaudio"` Mount the run directory inside the container and pass the unix domain socket as the argument of the environment variable `PULSE_SERVER`. This assumes that you want to leave pulseaudio running on your host! 

Example:
```
-v /run/user/1000/pulse:/run/user/1000/pulse \
-e PULSE_SERVER=unix:/run/user/1000/pulse/native \
```

**Comment by loose11** [comment]
Hello Jess, 
I dont want to open a new issue for this topic. Is their a walkthrough, how I can get the sound from the docker to the host? 

Because for example, when I am trying to watch a video over the Docker/Firefox I always receive this error:
`WARNING: Decoder=7f0efecc4200 [OnMediaSinkAudioError]`

**Comment by DestroyFX** [comment]
I did a strace and cat+grepped the offending thread.
Look like it's pulseaudio related

...
[pid 29822] connect(103, {sa_family=AF_UNIX, sun_path="/run/user/1000/pulse/native"}, 110) = 0
[pid 29822] send(68, "W", 1, MSG_NOSIGNAL) = -1 ENOTSOCK (Socket operation on non-socket)
[pid 29822] write(68, "W", 1)           = 1
[pid 29822] write(68, "W", 1)           = 1
[pid 29822] futex(0x58eb5170, FUTEX_UNLOCK_PI_PRIVATE) = 0
...

[crash.txt](https://github.com/jessfraz/dockerfiles/files/2344466/crash.txt)
