### ISSUE TITLE
Impossible to launch Chrome image on Ubuntu

### ISSUE THREAD

**Issue by wysow** [jfrazelle/dockerfiles#4]
Hello @jfrazelle!

First thanks for this awesome tricks!

I'm facing a problem when trying to launch your chrome image with the command line provided in your blog post, here is the error message:

```bash
WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
[1:1:0223/072428:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
No protocol specified
[1:1:0223/072428:ERROR:browser_main_loop.cc(210)] Gtk: cannot open display: unix:0
```

I'm a newbie with docker, can you help me? ;)

**Comment by seaninspace** [comment]
@wysow try this:

`$ xhost local:root`

:)

**Comment by wysow** [comment]
@seaninspace seems to do the trick, but afterwards my chrome user data seems to have been corrupted somehow...

**Comment by andreagrandi** [comment]
I was going to try this workaround (as I was having the same problem):

```
Unable to find image 'jess/chrome:latest' locally
Pulling repository jess/chrome
afd0b9ff8436: Download complete 
511136ea3c5a: Download complete 
8771fbfe935c: Download complete 
0e30e84e9513: Download complete 
51234c8e1d7b: Download complete 
717610759d79: Download complete 
b93129b92962: Download complete 
4596e961e5ab: Download complete 
91ef00dbf657: Download complete 
Status: Downloaded newer image for jess/chrome:latest
WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
[1:1:0223/101236:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
No protocol specified
[1:1:0223/101236:ERROR:browser_main_loop.cc(210)] Gtk: cannot open display: unix:0.0
```

but I can't risk to corrupt my user data, sorry :\

**Comment by jfrazelle** [comment]
If you are on a Mac please look at the other issues that have been closed.

On Monday, February 23, 2015, Andrea Grandi <notifications@github.com>
wrote:

> I was going to try this workaround (as I was having the same problem):
>
> Unable to find image 'jess/chrome:latest' locally
> Pulling repository jess/chrome
> afd0b9ff8436: Download complete
> 511136ea3c5a: Download complete
> 8771fbfe935c: Download complete
> 0e30e84e9513: Download complete
> 51234c8e1d7b: Download complete
> 717610759d79: Download complete
> b93129b92962: Download complete
> 4596e961e5ab: Download complete
> 91ef00dbf657: Download complete
> Status: Downloaded newer image for jess/chrome:latest
> WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
> [1:1:0223/101236:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
> No protocol specified
> [1:1:0223/101236:ERROR:browser_main_loop.cc(210)] Gtk: cannot open display: unix:0.0
>
> but I can't risk to corrupt my user data, sorry :\
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-75517577>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Seems like if the data is corrupt are you trying to use your old chrome
data from a diff version with the one in my image because that would be why

On Monday, February 23, 2015, Jessica Frazelle <me@jessfraz.com> wrote:

> If you are on a Mac please look at the other issues that have been closed.
>
> On Monday, February 23, 2015, Andrea Grandi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I was going to try this workaround (as I was having the same problem):
>>
>> Unable to find image 'jess/chrome:latest' locally
>> Pulling repository jess/chrome
>> afd0b9ff8436: Download complete
>> 511136ea3c5a: Download complete
>> 8771fbfe935c: Download complete
>> 0e30e84e9513: Download complete
>> 51234c8e1d7b: Download complete
>> 717610759d79: Download complete
>> b93129b92962: Download complete
>> 4596e961e5ab: Download complete
>> 91ef00dbf657: Download complete
>> Status: Downloaded newer image for jess/chrome:latest
>> WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
>> [1:1:0223/101236:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
>> No protocol specified
>> [1:1:0223/101236:ERROR:browser_main_loop.cc(210)] Gtk: cannot open display: unix:0.0
>>
>> but I can't risk to corrupt my user data, sorry :\
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-75517577>
>> .
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by andreagrandi** [comment]
Hi @jfrazelle is it possible instead to run the image in a completely isolated way so that it won't touch my existing Chrome installation? Cheers

**Comment by jfrazelle** [comment]
Yep the -v arguments in the commands can be removed, they are creating a
volume

On Monday, February 23, 2015, Andrea Grandi <notifications@github.com>
wrote:

> Hi @jfrazelle <https://github.com/jfrazelle> is it possible instead to
> run the image in a completely isolated way so that it won't touch my
> existing Chrome installation? Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-75572397>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
if its alright with you I am going to close this because I think it is just a misunderstanding with how it works ;)

**Comment by wysow** [comment]
Yep sure it's alright now, thanks.

**Comment by farhaanbukhsh** [comment]
Hey I am sorry I am commenting on  a closed issue I am running fedora 22 on macbook and I tried to run the same commands I am still getting the same error `[1:1:0123/155344:ERROR:browser_main_loop.cc(253)] Gtk: cannot open display: unix:0`

I have tried `xhost local:root` can you point me where am I going wrong?

**Comment by senrabdet** [comment]
Hi Jess - I was hoping you might have a quick suggestion on getting GUI apps to run on Docker on Windows (you helped me get past some issues before on Linux).  I'm getting what I think are X errors.  On Linux, all I had to do was add "host local:root" (like stated above), but on Windows I get an "bash: xhost: command not found".  When I try to start the firefox docker container, I get:

(process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' 
failed
(firefox:1): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Error: cannot open display: unix

Any thoughts?  Would you think I'd need to add something to my entire docker ENV, possibly to the Dockerfile, or run command?  If you have time....Thanks!

**Comment by jfrazelle** [comment]
This isn't going to work on Windows

On Friday, January 29, 2016, senrabdet <notifications@github.com> wrote:

> Hi Jess - I was hoping you might have a quick suggestion on getting GUI
> apps to run on Docker on Windows (you helped me get past some issues before
> on Linux). I'm getting what I think are X errors. On Linux, all I had to do
> was add "host local:root" (like stated above), but on Windows I get an
> "bash: xhost: command not found". When I try to start the firefox docker
> container, I get:
>
> (process:1): GLib-CRITICAL *
>
> *: g_slice_set_config: assertion 'sys_page_size == 0' failed (firefox:1):
> Gtk-WARNING **: Locale not supported by C library.
> Using the fallback 'C' locale.
> Error: cannot open display: unix
>
> Any thoughts? Would you think I'd need to add something to my entire
> docker ENV, possibly to the Dockerfile, or run command? If you have
> time....Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-176945220>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
OK, ugh (thanks Jess) - no way no how not ever?  Or some time down the 
road maybe?

**Comment by jfrazelle** [comment]
Unless you want to get x11 to work on windows which i have no idea why you
would ever

On Fri, Jan 29, 2016 at 12:10 PM, senrabdet <notifications@github.com>
wrote:

> OK, ugh (thanks Jess) - no way no how not ever? Or some time down the
> road maybe?
>
> On 01/29/2016 03:08 PM, Jess Frazelle wrote:
>
> > This isn't going to work on Windows
> >
> > On Friday, January 29, 2016, senrabdet <notifications@github.com> wrote:
> >
> > > Hi Jess - I was hoping you might have a quick suggestion on getting GUI
> > > apps to run on Docker on Windows (you helped me get past some issues
> > before
> > > on Linux). I'm getting what I think are X errors. On Linux, all I
> > had to do
> > > was add "host local:root" (like stated above), but on Windows I get an
> > > "bash: xhost: command not found". When I try to start the firefox
> docker
> > > container, I get:
> > >
> > > (process:1): GLib-CRITICAL *
> > >
> > > *: g_slice_set_config: assertion 'sys_page_size == 0' failed
> > (firefox:1):
> > > Gtk-WARNING **: Locale not supported by C library.
> > > Using the fallback 'C' locale.
> > > Error: cannot open display: unix
> > >
> > > Any thoughts? Would you think I'd need to add something to my entire
> > > docker ENV, possibly to the Dockerfile, or run command? If you have
> > > time....Thanks!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-176945220>
> > > .
> > >
> >
> >
> > --
> >
> >
> > Jessie Frazelle
> > 4096R / D4C4 DD60 0D66 F65A 8EFC 511E 18F3 685C 0022 BFF3
> > pgp.mit.edu
> > <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-176948508>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/4#issuecomment-176948983>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by senrabdet** [comment]
thanks again - was hoping to run browser in container, though maybe 
should just do in virtualbox in linux on windows ....(thanks again - you 
are a generous soul!)

Ted Barnes
Soholistic Networks
www.soholistic.net
(508) 277 9666

**Comment by tianon** [comment]
Hey don't be hating, Xming is pretty OK. :smile:

You're going to have to do something to pipe that socket through to your
containers, though (similar to the OS X hacks).

**Comment by senrabdet** [comment]
Thanks Tianon, appreciate the suggestion (will investigate)!

**Comment by tianon** [comment]
I _think_ that folks are using "socat" or something like it to share their
X server on OS X into the VM for using containers, and a similar hack will
likely work for Windows + Xming, but it's not going to be easy. :wink:

**Comment by senrabdet** [comment]
OK, thanks - as for being easy, at least for me, it never is....:)

**Comment by senrabdet** [comment]
A quick PS if I might (one thought, one question).  X2go runs on windows and osx, and got that to talk to a Docker container in virtualbox on the same pc over ssh without any hacking or work arounds....have torn it down as am going with how I interpreted Jess' thought that it's easier to just get into Virtualbox and do things there, but x2go is all setup to manage this type of connection if you're willing to violate the "one process per container idea"....in a big way.  My understanding is Docker and MS are coming out with containers for Windows so may be that will be an option too?

Also, would like to run a docker container as follows.
1)  in virtualbox, have a desktop running with menus (Mate in my case)
2)  add a menu launcher to start a container probably aimed at a simple bash script
3)  run that container from the menu as the logged in user (regular, standard user)
4) avoid adding the user to the docker group....on the assumption that gives the regular user too much access to the docker daemon
My sense is existing apps like Firefox do this somehow in common, popular linux desktop environments using soft links but I've been unable to emulate that approach.

If I'm posting this in the wrong place, please let me know (and a suggestion where to post properly if possible?).

Any suggestions?  As usual, thanks so much!

**Comment by beevik** [comment]
Just a quick note as I was playing with this (cool!) container:

I removed the "-it" option to "docker run", since it was preventing me from backgrounding the launching of chrome.  (Also, I don't think there's any reason to have interactive tty input on a gui app like chrome.)

**Comment by timrsfo** [comment]
I'm also trying to start up chrome

Running on Ubuntu 14.04
$ xhost local:root   #  command executed first
Running jess/chrome with recommended docker run ... command.
tried both: jess/chrome and jess/chrome:beta

Chrome starts up but I get a lot of WARNING and ERROR msgs
- What can be done to clean up all these error/warnings?
- or are these all considered ok?

WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
Gtk-Message: Failed to load module "canberra-gtk-module"
[1:23:0729/233628:**ERROR**:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
shared memfd open() failed: Function not implemented
process 1: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.

(google-chrome:1): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
/usr/bin/dbus-launch terminated abnormally without any error message
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
[220:220:0729/233629:**ERROR**:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[1:35:0729/233629:**ERROR**:browser_gpu_channel_host_factory.cc(131)] Failed to create channel.

(google-chrome:1): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file '/var/lib/dbus/machine-id': No such file or directory
[1:656:0729/233646:**ERROR**:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

**Comment by senrabdet** [comment]
Hi All:
 
May have made some progress on this....hope maybe it is helpful?  Jess mentions in some of her posts that she uses a custom kernel.  Had help finding post below that tweaks Debian and friend who found post for me also said he got it to work on Ubuntu.  FYI (caveats) - I use this in virtualbox to head off munging my system; so far seems to work well, but don't know if it introduces collateral problems including security issues or whether others can made it work without problems.....as a work around, there are probably better answers.
 
Post found and used is:  https://myles.sh/configuring-lxc-unprivileged-containers-in-debian-jessie/  (I'm actually using it in Stretch).  Thanks to Myles!  My (limited) understanding at this point is that Debian says it enables namespaces, but really only partially enables and partially cripples them, hence the problem in running Chrome in containers including Jess' cool stuff.  
 
Per the post, only did step 2 (I did all of this as root, so the sudo for me was immaterial).  I suspect this is a bit of a kludge, but after a lot of searching without avail, it is the only approach I've found to work and is what I'm using at present (code here is lifted directly from Myle's URL):
 
touch /etc/sysctl.d/80-lxc-userns.conf
echo "kernel.unprivileged_userns_clone=1" > etc/sysctl.d/80-lxc-userns.conf
sudo sysctl --system
sudo apt-get install uidmap -y
sudo usermod --add-subuids 100000-165536 $USER
sudo usermod --add-subgids 100000-165536 $USER
touch /root/.config/lxc/default.conf
echo "lxc.id_map = u 0 100000 65536" > /root/.config/lxc/default.conf
echo "xc.id_map = g 0 100000 65536" >> /root/.config/lxc/default.conf
 
reboot
 
Once I did this, Jess' stuff worked and url in chrome of "chrome://sandbox" shows:
Sandbox Status    SUID Sandbox No   Namespace Sandbox Yes   PID namespaces Yes   Network namespaces Yes   Seccomp-BPF sandbox Yes   Seccomp-BPF sandbox supports TSYNC Yes   Yama LSM enforcing No   
 You are adequately sandboxed.
 
 
Will be curious to see if this works for others... 


 
 
--------- Original Message --------- Subject: Re: [jfrazelle/dockerfiles] Impossible to launch Chrome image on Ubuntu (#4)

**Comment by nunobaba** [comment]
For a while, my container running chromium on arch could connect to the X server and start as it should. The `xhost +` command plus passing `--privileged` flag did the trick. For some reasons and without any modification of the container or the host config, it doesn't. I know this sounds a bit vague as a description, but is there any other else I can do to solve this? Thanks.

**Comment by senrabdet** [comment]
Are you running on Debian?
 
 
 
 
--------- Original Message --------- Subject: Re: [jfrazelle/dockerfiles] Impossible to launch Chrome image on Ubuntu (#4)

**Comment by nunobaba** [comment]
On Arch. The problem got solved by itself after upgrading a bunch of stuff
including linux kernel, linux headers and xorg server. Thanks for asking.
