### ISSUE TITLE
Can X be connected to / forwarded out of the Docker host?

### ISSUE THREAD

**Issue by tom472** [jfrazelle/dockerfiles#43]
I have been testing some of these X App images like Chrome and VLC etc.
When I am on a Linux PC and run:

docker run -d  -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY  --name chrome jess/chrome

The Chrome app container opens and works perfectly - just as expected.

Sometimes when I am at work I need to test some things by simulating an "outside" connection so when this comes up I use my VPS and generally start a lightweight browser and forward that over X.
i.e.
ssh -X tom@my.v.p.s 
$ midori 2>/dev/null &
That will send Midori to my local PC so I can test some things as if I were outside my network.
I would really love to be able to pull Midori, and all the extra nonsense that it needed, from my VPS and use your Chrome Docker container to simulate the external testing.

However - when I am ssh'd into my VPS and run the same command it does not send Chrome to my local machine.
If I re-run it with -it instead of -d the error I get is:
Gtk: cannot open display: unixlocalhost:10.0
I have tried running: xhost +local:docker
 -and- 
sudo xhost +local:docker (As seen here: https://registry.hub.docker.com/u/jess/chrome/)
But the error remains.

I guess my first question would be is this something that can be done / accomplished?
And if yes - I am guessing there is some tweaking that needs to be done to my VPS - or there are some different / additional Docker switches that need to be passed to get it to run.

Any help / suggestions would be really appreciated.

Thanks
--Tom

**Comment by tom472** [comment]
So after doing some more research and looking into this I believe I have found an article that outlines the steps / process to get to what I am after.
This is the article I found:
https://blog.docker.com/2013/07/docker-desktop-your-desktop-over-ssh-running-inside-of-a-docker-container/

I am going to try and use this as a guide and see if I can be successful.
As this article looks to be a little bit involved - if anyone has any other suggestions / options please feel free to post them.

Going to mark this as closed however as I believe I have a path to follow now.

Thanks
--Tom

**Comment by rozy11a** [comment]
hi @tom472 did it work? because I couldn't make it work so far
