### ISSUE TITLE
create official unshare variant for ARM

### ISSUE THREAD

**Issue by Govinda-Fichtner** [jfrazelle/dockerfiles#73]
While trying to get Docker integration tests running on ARM one major problem is that the current unshare image only works for x86.

Together with @stefanscherer I created a quick'n'dirty variant of the unshare image which can be found here: https://github.com/hypriot/armhf-unshare

As the unshare image is used for the integration tests makes me think that it also should be part of the official docker-library. Same as for the busybox image.

How could we best achieve this? How could I help?

**Comment by jfrazelle** [comment]
I would say checking out the process in github.com/docker-library/official-images

**Comment by Govinda-Fichtner** [comment]
@jfrazelle Just to make it clear: you agree that the images used in the integrations tests should be part of the docker-library/official-images?

**Comment by jfrazelle** [comment]
eventually yes, but for now we can use personal repos

On Fri, Oct 30, 2015 at 3:18 AM, Govinda Fichtner <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> Just to make it clear: you
> agree that the images used in the integrations tests should be part of the
> docker-library/official-images?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/73#issuecomment-152484211>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by tianon** [comment]
I'm still hazy on what makes the unshare image different from the unshare
binary included in the Debian base image itself?

**Comment by jfrazelle** [comment]
ya so it was supposed to be bad version of unshare iirc pinng @ewindisch

On Fri, Oct 30, 2015 at 10:28 AM, Tianon Gravi <notifications@github.com>
wrote:

> I'm still hazy on what makes the unshare image different from the unshare
> binary included in the Debian base image itself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/issues/73#issuecomment-152594450>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by ewindisch** [comment]
@jfrazelle @tianon The problem is/was that some versions of unshare don't work appropriately on all kernels. The jess/unshare image is of a version that is "mostly compatible" across different kernels. Also, it's really small.

If the version of unshare in the latest debian image works well across kernels, then by all means, use it instead.
