### ISSUE TITLE
Expand explanation on pulseaudio crashing

### ISSUE THREAD

**Issue by senrabdet** [jfrazelle/dockerfiles#75]
Hi jess - I am hoping you might expand on the solution noted in closed issue #38 re; pulseaudio crashing (I would also echo how great your container work is!).  Am having same trouble as xinity, and am unclear how this was solved. I'm trying to get the Tor and pulseaudio containers to link (in virtualbox Centos 7, Mate VMs).  Like xinity, I have pulseaudio running on the host but have tried uninstalling it with no joy.  I think pulseaudio is crashing with same errors shown in #38.   Did solution "adapt my host config" mean changing the "HostConfig object" in a way that pierces the container and is there a URL you could suggest on how to do this? Does this introduce security issues by having the container use the host in this way and if so, is there another way to get my pulseaudio container to work? I'm using Docker 1.8.3. Thanks!

**Comment by jfrazelle** [comment]
Hey I responded on the old issue you don't need a new one

**Comment by senrabdet** [comment]
Apologies (and thanks so much for the help)

Ted Barnes
Soholistic Networks
www.soholistic.net
(508) 277 9666

**Comment by jfrazelle** [comment]
No worries :)






On Fri, Oct 30, 2015 at 7:54 AM -0700, "senrabdet" <notifications@github.com> wrote:










Apologies (and thanks so much for the help)



Ted Barnes

Soholistic Networks

www.soholistic.net

(508) 277 9666
