### ISSUE TITLE
sublime-text-3: Unable to find image 'Dockerfile:latest' locally

### ISSUE THREAD

**Issue by zddhub** [jfrazelle/dockerfiles#89]
I only copied Dockerfile, build correct but when I run:

Unable to find image 'Dockerfile:latest' locally
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"

CMD ["/usr/src/sublime_text/sublime_text", "-w"]
localhost:docker-test zdd$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by koep** [comment]
Please post the exact commands that you used (to build the image and to run the container).

**Comment by zddhub** [comment]
Thanks koep for your response.

build command:
$ docker build -t sublime-text:3 .

run command:
$ docker run -it \
	-v $HOME/.config/sublime-text-3/:/root/.config/sublime-text-3 \
	-v $HOME/development:/root/development \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-e DISPLAY=$DISPLAY sublime-text:3

**Comment by koep** [comment]
This does not make any sense. Your error message indicates that you try to run an image named 'Dockerfile:latest'. 

Could you provide a screenshot of your terminal or something?

**Comment by zddhub** [comment]
Thanks koep, Everything goes well when I installed xquartz as following this link: http://learning-continuous-deployment.github.io/docker/images/dockerfile/2015/04/22/docker-gui-osx/
